### ISSUE TITLE
Multiple test compare with zeros in the end

### ISSUE THREAD

**Issue by guissalustiano** [PCS3616/laboratorio-06#3]
[A implementação do miguel ](https://github.com/PCS3616/lab06-11807601-12554230) está correta mas não passa na correção
![image](https://user-images.githubusercontent.com/32439070/224520343-c12f899e-b909-47ae-aa0d-3a2cd37972f5.png)
 
 O `teste_dumper_multiple` espera 6 bytes zero no final do arquivo, quando não deveria.

**Comment by tomaz-suller** [comment]
Acho que a gente já discutiu isso, mas o comportamento esperado é ter os zeros no final, certo? Ou seja, a gente pode fechar essa issue

**Comment by guissalustiano** [comment]
Sim, ele espera esses zeros no final para o loader conseguir ler
